name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Retrieve UserPoolId from Cloudformation 
        id: retrieve-cognitouserpoolid
        run: echo "COGNITO_USER_POOL_ID=$(aws cloudformation --region eu-west-1 describe-stacks --stack-name fromagerie-virtuelle --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text)" >> $GITHUB_OUTPUT
      - name: Retrieve CognitoUserPoolId from Cloudformation 
        id: retrieve-cognitoclientid
        run: echo "COGNITO_CLIENT_ID=$(aws cloudformation --region eu-west-1 describe-stacks --stack-name fromagerie-virtuelle --query "Stacks[0].Outputs[?OutputKey=='CognitoClientId'].OutputValue" --output text)" >> $GITHUB_OUTPUT
      # TODO
      # - name: Retrieve Distribution ID from Cloudformation 
      #   id: retrieve-cognitouserpoolid
      #   run: echo "COGNITO_USER_POOL_ID=$(aws cloudformation --region eu-west-1 describe-stacks --stack-name fromagerie-virtuelle --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text)" >> $GITHUB_OUTPUT
      # - name: Retrieve S3 Bucket name from Cloudformation 
      #   id: retrieve-cognitoclientid
      #   run: echo "COGNITO_CLIENT_ID=$(aws cloudformation --region eu-west-1 describe-stacks --stack-name fromagerie-virtuelle --query "Stacks[0].Outputs[?OutputKey=='CognitoClientId'].OutputValue" --output text)" >> $GITHUB_OUTPUT
      - run: npm ci
      - run: S3_BUCKET_ADDRESS=${{ steps.xxxx.yyyy }} REACT_APP_COGNITO_USER_POOL_ID=${{ steps.retrieve-cognitouserpoolid.COGNITO_USER_POOL_ID }} REACT_APP_COGNITO_USER_POOL_ID=${{ steps.retrieve-cognitoclientid.COGNITO_CLIENT_ID }} npm run build
      - run: npm run copy-to-s3
      - run: CLOUDFRONT_DISTRIBUTION_ID=${{ steps.xxxx.yyyy }} npm run invalidate-cloudfront
  
